"""Structured state models for the network digital twin."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


def utc_now_iso() -> str:
    """Return the current UTC timestamp in ISO 8601 format."""

    return datetime.now(timezone.utc).isoformat()


@dataclass(slots=True)
class PortState:
    """Structured state for a switch port."""

    port_no: int
    rx_packets: int = 0
    tx_packets: int = 0
    rx_bytes: int = 0
    tx_bytes: int = 0
    is_up: bool = True

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class SwitchState:
    """Structured state for a network switch."""

    dpid: str
    name: str
    city: str | None = None
    country: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    ports: list[PortState] = field(default_factory=list)
    flow_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["ports"] = [port.to_dict() for port in self.ports]
        return payload


@dataclass(slots=True)
class LinkState:
    """Structured state for a logical link between two switch ports."""

    src_dpid: str
    dst_dpid: str
    src_port: int
    dst_port: int
    is_up: bool = True
    latency_ms: float = 0.0
    label: str | None = None
    distance_km: float | None = None
    bandwidth_mbps: int | None = None

    def key(self) -> str:
        """Return a stable identifier for the undirected link."""

        first = (self.src_dpid, self.src_port)
        second = (self.dst_dpid, self.dst_port)
        left, right = sorted((first, second))
        return f"{left[0]}:{left[1]}--{right[0]}:{right[1]}"

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["link_id"] = self.key()
        return payload


@dataclass(slots=True)
class HostState:
    """Structured state for a network host."""

    name: str
    ip: str
    mac: str
    attached_switch: str
    attached_port: int

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EventRecord:
    """Structured event generated by state differences or sync failures."""

    timestamp: str
    event_type: str
    entity_type: str
    entity_id: str
    old_value: Any
    new_value: Any
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class NetworkState:
    """Structured network state snapshot maintained by the twin."""

    timestamp: str
    switches: list[SwitchState] = field(default_factory=list)
    links: list[LinkState] = field(default_factory=list)
    hosts: list[HostState] = field(default_factory=list)

    def link_index(self) -> dict[str, LinkState]:
        """Index links by their stable identifier."""

        return {link.key(): link for link in self.links}

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "switches": [switch.to_dict() for switch in self.switches],
            "links": [link.to_dict() for link in self.links],
            "hosts": [host.to_dict() for host in self.hosts],
        }
