#!/usr/bin/env bash
set -euo pipefail

export INITIALIZATION_TIMEOUT_SECONDS="${INITIALIZATION_TIMEOUT_SECONDS:-60}"
export SCENARIO_TIMEOUT_SECONDS="${SCENARIO_TIMEOUT_SECONDS:-60}"
export BACKGROUND_PING_INTERVAL="${BACKGROUND_PING_INTERVAL:-0.2}"
export REPEAT="${REPEAT:-10}"
export LOAD_LEVELS="${LOAD_LEVELS:-10 30 50 80}"
export RANDOMIZE_LOAD_ORDER="${RANDOMIZE_LOAD_ORDER:-true}"
export RANDOM_SEED="${RANDOM_SEED:-20260425}"
